genSimpleMultisigGo:
	abigen -sol ./contracts/SimpleMultiSig.sol -pkg multisig_gen --out ./multisig_gen/SimpleMultiSig.g.go
genDynamicMultisigGo:
	abigen -sol ./contracts/DynamicMultiSig.sol -pkg multisig_gen --out ./multisig_gen/DynamicMultiSig.g.go
genERC20Go:
	abigen -sol ./contracts/ERC20Minter.sol -pkg erc20_gen --out ./erc20_gen/ERC20Minter.g.go